version: "3.7"

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - ${DATA_FOLDER}/caddy_config:/config
      - ${DATA_FOLDER}/caddy_config/Caddyfile:/etc/caddy/Caddyfile
      - /opt/avionai/local_files:/srv
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - 5678:5678
    environment:
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - N8N_SECURE_COOKIE=false
      - N8N_PROTOCOL=http
      - NODE_FUNCTION_ALLOW_BUILTIN=${NODE_FUNCTION_ALLOW_BUILTIN}
      - NODE_FUNCTION_ALLOW_EXTERNAL=${NODE_FUNCTION_ALLOW_EXTERNAL}

    volumes:
      - /opt/paddleocr:/opt/paddleocr
      - n8n_data:/home/node/.n8n
      - ${DATA_FOLDER}/local_files:/files

  xlsx-service:
    build:
      context: ./caddy_config  # or wherever you place main.py/Dockerfile
    container_name: avionai-xlsx
    volumes:
      - /opt/avionai/local_files/output_template:/templates:ro
    networks:
      - avionai_default  # same network as n8n/caddy
    restart: unless-stopped
    ports:
      - "8001:8000"   # or keep internal-only and reverse-proxy via Caddy

volumes:
  caddy_data:
    external: true
  n8n_data:
    external: true

